version: '3.4'
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - app
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8088:8088
    networks:
      - app

networks:
  app: